# 数据清洗

In [2]:
#导入需要使用的库
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [4]:
#使用pandas读取数据
train = pd.read_csv("inputs/train.csv")
test = pd.read_csv("inputs/test.csv")
store = pd.read_csv("inputs/store.csv")

/Users/limao/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [7]:
#查看train数据的前五行
train.head(5)

Store  DayOfWeek        Date  Sales  Customers  Open  Promo StateHoliday  \
0      1          5  2015-07-31   5263        555     1      1            0   
1      2          5  2015-07-31   6064        625     1      1            0   
2      3          5  2015-07-31   8314        821     1      1            0   
3      4          5  2015-07-31  13995       1498     1      1            0   
4      5          5  2015-07-31   4822        559     1      1            0   

   SchoolHoliday  
0              1  
1              1  
2              1  
3              1  
4              1

In [18]:
#查看train中每个特征的unique值
feature_list = train.columns.values.tolist()
for feature in feature_list:
    print('{} 唯一值数量:'.format(feature),len(train[feature].unique()))

Store 唯一值数量: 1115
DayOfWeek 唯一值数量: 7
Date 唯一值数量: 942
Sales 唯一值数量: 21734
Customers 唯一值数量: 4086
Open 唯一值数量: 2
Promo 唯一值数量: 2
StateHoliday 唯一值数量: 5
SchoolHoliday 唯一值数量: 2


In [19]:
#unique值检查中发现StateHoliday有异常.检查发现是有把数字0和字符‘0’混淆
train.StateHoliday.unique()

array(['0', 'a', 'b', 'c', 0], dtype=object)

In [29]:
#检查train数据集是否有空缺值
train.isnull().any(axis=0)

Store            False
DayOfWeek        False
Date             False
Sales            False
Customers        False
Open             False
Promo            False
StateHoliday     False
SchoolHoliday    False
dtype: bool

In [8]:
#打印train训练集的信息
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
Store            1017209 non-null int64
DayOfWeek        1017209 non-null int64
Date             1017209 non-null object
Sales            1017209 non-null int64
Customers        1017209 non-null int64
Open             1017209 non-null int64
Promo            1017209 non-null int64
StateHoliday     1017209 non-null object
SchoolHoliday    1017209 non-null int64
dtypes: int64(7), object(2)
memory usage: 69.8+ MB


In [9]:
#查看store数据集的前五行
store.head()

Store StoreType Assortment  CompetitionDistance  CompetitionOpenSinceMonth  \
0      1         c          a               1270.0                        9.0   
1      2         a          a                570.0                       11.0   
2      3         a          a              14130.0                       12.0   
3      4         c          c                620.0                        9.0   
4      5         a          a              29910.0                        4.0   

   CompetitionOpenSinceYear  Promo2  Promo2SinceWeek  Promo2SinceYear  \
0                    2008.0       0              NaN              NaN   
1                    2007.0       1             13.0           2010.0   
2                    2006.0       1             14.0           2011.0   
3                    2009.0       0              NaN              NaN   
4                    2015.0       0              NaN              NaN   

     PromoInterval  
0              NaN  
1  Jan,Apr,Jul,Oct  
2  Jan,Apr,Jul,Oct  
3              NaN  
4              NaN

In [23]:
for column in store:
    print('{} 的唯一值:'.format(column),len(store[column].unique()))

Store 的唯一值: 1115
StoreType 的唯一值: 4
Assortment 的唯一值: 3
CompetitionDistance 的唯一值: 655
CompetitionOpenSinceMonth 的唯一值: 13
CompetitionOpenSinceYear 的唯一值: 24
Promo2 的唯一值: 2
Promo2SinceWeek 的唯一值: 25
Promo2SinceYear 的唯一值: 8
PromoInterval 的唯一值: 4


In [24]:
#CompetitionOpenSinceMonth 有13个unique值，检查发现是有nan，应该代表具体月份不详
store.CompetitionOpenSinceMonth.unique()

array([ 9., 11., 12.,  4., 10.,  8., nan,  3.,  6.,  5.,  1.,  2.,  7.])

In [25]:
#PromoInterval 只有 4个unique值，查看一下
store.PromoInterval.unique()

array([nan, 'Jan,Apr,Jul,Oct', 'Feb,May,Aug,Nov', 'Mar,Jun,Sept,Dec'],
      dtype=object)

In [31]:
#检查store数据集是否有空缺值.发现CompetitionDistance等列有空缺值，分析应该是表示该行的Store没有竞争对手，所以含有competition三列为NaN
#Promo2为0情况下，自然Promo2SinceWeek/Year列为NaN
store.isnull().any(axis=0)

Store                        False
StoreType                    False
Assortment                   False
CompetitionDistance           True
CompetitionOpenSinceMonth     True
CompetitionOpenSinceYear      True
Promo2                       False
Promo2SinceWeek               True
Promo2SinceYear               True
PromoInterval                 True
dtype: bool

In [10]:
store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 10 columns):
Store                        1115 non-null int64
StoreType                    1115 non-null object
Assortment                   1115 non-null object
CompetitionDistance          1112 non-null float64
CompetitionOpenSinceMonth    761 non-null float64
CompetitionOpenSinceYear     761 non-null float64
Promo2                       1115 non-null int64
Promo2SinceWeek              571 non-null float64
Promo2SinceYear              571 non-null float64
PromoInterval                571 non-null object
dtypes: float64(5), int64(2), object(3)
memory usage: 87.2+ KB


In [26]:
test.head()

Id  Store  DayOfWeek        Date  Open  Promo StateHoliday  SchoolHoliday
0   1      1          4  2015-09-17   1.0      1            0              0
1   2      3          4  2015-09-17   1.0      1            0              0
2   3      7          4  2015-09-17   1.0      1            0              0
3   4      8          4  2015-09-17   1.0      1            0              0
4   5      9          4  2015-09-17   1.0      1            0              0

In [27]:
for feature in test:
    print('{} 唯一值数量:'.format(feature),len(test[feature].unique()))

Id 唯一值数量: 41088
Store 唯一值数量: 856
DayOfWeek 唯一值数量: 7
Date 唯一值数量: 48
Open 唯一值数量: 3
Promo 唯一值数量: 2
StateHoliday 唯一值数量: 2
SchoolHoliday 唯一值数量: 2


In [28]:
#test 中open的数量为3，检查发现有NaN
test.Open.unique()

array([ 1., nan,  0.])

In [32]:
#检查test中空缺值
test.isnull().any(axis=0)


Id               False
Store            False
DayOfWeek        False
Date             False
Open              True
Promo            False
StateHoliday     False
SchoolHoliday    False
dtype: bool

## 对空缺值做处理

In [33]:
#store中的NaN用0填充
store.fillna(0,inplace = True)

#test中的NaN用1填充
test.fillna(1,inplace = True)